name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_social_button: ^1.1.6+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  icon_icons: ^1.0.4
  url_launcher: ^6.3.1
  velocity_x: ^4.2.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Ecommerceproject.mp4
    - assets/WeatherProjectVideo.mp4
    - assets/Ecommerceproject2.mp4
    - assets/WeatherProjectVideo2.mp4
    - assets/background.jpg
    - assets/profile.jpg
    - assets/background.png
    - assets/back1.png
    - assets/back2.png
    - assets/flutterLogo.png
    - assets/nodeLogo.jpg
    - assets/cloudLogo.png
    - assets/toolLogo.png
    - assets/plLogo.jpg
    - assets/cloud2Logo.png
    - assets/frontendLogo.png
    - assets/backendLogo.png
    - assets/crossLogo.png
    - assets/GitLogo.png
    - assets/DownloadLogo.png
    - assets/fbLogo.png
    - assets/whatsappLogo.png
    - assets/phoneLogo.png
    - assets/linkdenLogo.png
    - assets/mailLogo.png
    - assets/githubLogo.png
    - assets/profile2.png